trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'acr-docker-connection'
  acrLoginServer: 'bratvaa.azurecr.io'
  imageName: 'nodejs-app'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        pool:
          name: 'bratva'
         
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
            displayName: 'Build nodejs-app'
            workingDirectory: node-app


          - task: Docker@2
            inputs:
              command: buildAndPush
              repository: $(acrLoginServer)/$(imageName)
              dockerfile: app/Dockerfile
              buildContext: app                  # <-- add this line
              containerRegistry: $(azureSubscription)
              tags: |
                $(Build.BuildId)
            displayName: 'Build and Push Docker image to ACR'
